### ISSUE TITLE
Faking user activation is dangerous & can spam users at a minimum with permission requests & installation requests

### ISSUE THREAD

**Issue by dmurph** [duckduckgo/autoconsent#443] opened 2024-05-14 19:34 UTC
See https://github.com/ghostery/ghostery-extension/issues/1582.

Dangerous web APIs are protected by user activation, and by faking this it can allow sites to do annoying behavior at a minimum, and malicious behavior at worst.

I don't have an index of all APIs that require user gesture - but any permission request is often guarded by them, showing a PWA installation prompt is another, etc.

**Comment by dmurph** [comment] 2024-05-14 19:34
Try using ghostery and visiting parkseed.com, and clicking on anything to navigate.

**Comment by dmurph** [comment] 2024-05-15 23:03
More things that can happen:
- audio autoplay is blocked until user activation. This allows sites to auto-play music or videos with audio.
- fullscreen is blocked on user activation. This allows sites to make themselves fullscreen.

See more APIs that reference sticky activation [here](https://dontcallmedom.github.io/webdex/s.html#Sticky%20activation%40%40html%25%25dfn) and user activation [here](https://dontcallmedom.github.io/webdex/u.html#user%20activation%40%40html%25%25dfn). That means something in that spec is guarded on user activation. there may be more terms, I'm not sure (hard to look up list of all things that use user activation).

**Comment by muodov** [comment] 2024-05-16 08:44
Hi @dmurph, I tried to open parkseed.com, but could not reproduce any issues neither with autoconsent extension, nor with Ghostery. I was using Chrome 125 on macOS.

Autoconsent is a content script, and all its interactions are programmatic (literally calling `.click()` on some DOM nodes). This means that the corresponding click events are not trusted (`event.isTrusted === false`), and as far as I know, those events should not affect browser features that require a real user gesture, such as autoplay and fullscreen.

I am also confused how this particular site (parkseed.com) could be affected, since there are no autoconsent rules that match this site, so it should not even try to click anything there.

Could you please try to reproduce using the autoconsent extension (you can build it with `npm install && npm run prepublish`), and see if you get the same issue? If not, it might be Ghostery-specific. If yes, I'll probably need more details to reproduce.

**Comment by philipp-classen** [comment] 2024-05-16 11:00
About how to reproduce with Ghostery:

When I tried last week, it was straightforward to reproduce (installing Ghostery on Chrome, visit parkseed.com, and clicking through the menu). I got the install prompt popping on each navigation. However, when I tried the same steps yesterday, I also was unable to reproduce it any longer.

I am not aware of any changes on the Ghostery side, so maybe the test website changed? For me, it went from trivial to reproduce now to unable to reproduce. If I hear of a way to reliably trigger it again, I will share here as well.

**Comment by dmurph** [comment] 2024-05-16 23:29
I created a test site here: https://motley-petite-friday.glitch.me/

**Comment by philipp-classen** [comment] 2024-05-17 09:38
> I created a test site here: https://motley-petite-friday.glitch.me/

Thanks for that! With this test site, I could reproduce it again with Ghostery 8 on Chrome. But for me, neither the DuckDuckGo Privacy Essentials extension, nor the upcoming Ghostery 10 release is affected. Given that we will upgrade to Ghostery 10 in the near future anyway - a full rewrite to support Manifest V3 - there is a good chance it will be solved when we roll it out.

So, based on my current understanding, it is not an issue in the autoconsent library. For Ghostery specific parts, we can move the discussion back to https://github.com/ghostery/ghostery-extension/issues/1582

**Comment by muodov** [comment] 2024-05-17 10:34
@dmurph thank you for the test page!
I could reproduce the PWA pop-up with Ghostery, but not with autoconsent, so I think @philipp-classen is right.

@philipp-classen just to eliminate confusion, DuckDuckGo Privacy Essentials is not using autoconsent at the moment.

I am going to close this issue since it seems unrelated to autoconsent.

**Closed by muodov** 2024-05-17 10:34 UTC
